"""Initial schema

Revision ID: b95bd56b151c
Revises: 
Create Date: 2026-04-20 03:27:42.482996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b95bd56b151c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('target_role', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('resume_projects',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.user_id'], ),
    sa.PrimaryKeyConstraint('resume_id')
    )
    op.create_index(op.f('ix_resume_projects_resume_id'), 'resume_projects', ['resume_id'], unique=False)
    op.create_table('resume_sections',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('section_type', sa.Enum('SUMMARY', 'EXPERIENCE', 'PROJECT', 'SKILLS', 'CERTIFICATIONS', 'ACHIEVEMENTS', 'EDUCATION', name='sectiontype'), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume_projects.resume_id'], ),
    sa.PrimaryKeyConstraint('section_id')
    )
    op.create_index(op.f('ix_resume_sections_section_id'), 'resume_sections', ['section_id'], unique=False)
    op.create_table('experience_duties',
    sa.Column('duty_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['resume_sections.section_id'], ),
    sa.PrimaryKeyConstraint('duty_id')
    )
    op.create_index(op.f('ix_experience_duties_duty_id'), 'experience_duties', ['duty_id'], unique=False)
    op.create_table('generative_options',
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('duty_id', sa.UUID(), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['duty_id'], ['experience_duties.duty_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_index(op.f('ix_generative_options_option_id'), 'generative_options', ['option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generative_options_option_id'), table_name='generative_options')
    op.drop_table('generative_options')
    op.drop_index(op.f('ix_experience_duties_duty_id'), table_name='experience_duties')
    op.drop_table('experience_duties')
    op.drop_index(op.f('ix_resume_sections_section_id'), table_name='resume_sections')
    op.drop_table('resume_sections')
    op.drop_index(op.f('ix_resume_projects_resume_id'), table_name='resume_projects')
    op.drop_table('resume_projects')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
